name: sid_hymnal
description: SID Seventh-day Adventist Hymnal
version: 1.0.6+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.1

  shared_preferences: ^0.5.6+1

  flutter_markdown: ^0.3.3

  audioplayers: ^0.14.0

  cupertino_icons: ^0.1.3

  onesignal_flutter: ^2.0.0

  share: ^0.6.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
# run this command:
# -------------
# "flutter pub run flutter_launcher_icons:main" 
# -------------
# to generate icons

flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/audio/
    - assets/hymns/
    - assets/hymns/en/
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"
  